from pathlib import Path
p=Path('/mnt/data/accounting-repair/components/accounting/AccountingWorkspace.tsx')
s=p.read_text()
s=s.replace('import { useMemo, useRef, useState } from "react";','import { useMemo, useRef, useState } from "react";')
old='''  cashMovement\n}: {\n  jobs: AccountingJob[];\n  expenses: AccountingExpense[];\n  openingBalance: OpeningBalance | null;\n  accountingUserId: string;\n  currentMonth: string;\n  cashMovement: { collections: number; releases: number; commissionPayouts: number; paidExpenses: number };\n}) {'''
new='''  cashMovement,\n  dashboardMetrics,\n  cashTrend\n}: {\n  jobs: AccountingJob[];\n  expenses: AccountingExpense[];\n  openingBalance: OpeningBalance | null;\n  accountingUserId: string;\n  currentMonth: string;\n  cashMovement: { collections: number; releases: number; commissionPayouts: number; paidExpenses: number };\n  dashboardMetrics: { currentCash: number; receivable: number; revenue: number; profit: number };\n  cashTrend: { month: string; collections: number; releases: number; expenses: number }[];\n}) {'''
assert old in s
s=s.replace(old,new)
# Replace totals block fields with authoritative metrics for four cards, keep other calculations
old2='''    return { revenue, received, receivable, estimatedCost, actualCost, released, paidCommissions, paidExpenses, openingCash, currentCash: openingCash + cashMovement.collections - cashMovement.releases - cashMovement.commissionPayouts - cashMovement.paidExpenses };'''
new2='''    return { revenue, received, receivable, estimatedCost, actualCost, released, paidCommissions, paidExpenses, openingCash, currentCash: dashboardMetrics.currentCash, dashboardReceivable: dashboardMetrics.receivable, dashboardRevenue: dashboardMetrics.revenue, dashboardProfit: dashboardMetrics.profit };'''
assert old2 in s
s=s.replace(old2,new2)
# Add report filter state after busy
needle='''  const [busy, setBusy] = useState(false);'''
replace='''  const [busy, setBusy] = useState(false);\n  const [reportRange, setReportRange] = useState<"3m" | "6m" | "12m">("6m");'''
s=s.replace(needle,replace)
# Replace overview metric section
old3='''          <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">\n            <Metric label="Current cash position" value={peso(totals.currentCash)} />\n            <Metric label="Customer receivables" value={peso(totals.receivable)} />\n            <Metric label="Revenue on approved jobs" value={peso(totals.revenue)} />\n            <Metric label="Estimated job profit" value={peso(totals.revenue - totals.estimatedCost)} />\n          </section>'''
new3='''          <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">\n            <Metric label="Current cash position" value={peso(totals.currentCash)} hint="Live cash trail" />\n            <Metric label="Customer receivables" value={peso(totals.dashboardReceivable)} hint="Approved revenue less recorded payments" />\n            <Metric label="Revenue on approved jobs" value={peso(totals.dashboardRevenue)} hint="Active + completed approved jobs" />\n            <Metric label="Estimated job profit" value={peso(totals.dashboardProfit)} hint="Revenue less current job cost records" />\n          </section>\n          <Panel title="Cash movement trend" right={<div className="flex items-center gap-1 rounded-lg bg-gray-50 p-1">{([['3m','3 months'],['6m','6 months'],['12m','12 months']] as const).map(([id,label]) => <button key={id} onClick={() => setReportRange(id)} className={`rounded-md px-2.5 py-1 text-[10px] font-semibold ${reportRange === id ? 'bg-gray-900 text-white' : 'text-gray-500 hover:bg-white'}`}>{label}</button>)}</div>}>\n            <CashTrendChart data={cashTrend.slice(reportRange === "3m" ? -3 : reportRange === "6m" ? -6 : -12)} />\n          </Panel>'''
assert old3 in s
s=s.replace(old3,new3)
# Reports replace section with richer filter and movement
old4='''      {tab === "reports" && (\n        <div className="grid gap-5 lg:grid-cols-2">\n          <Panel title="Monthly performance"><div className="space-y-2 text-sm"><Line label="Revenue" value={peso(totals.revenue)} strong /><Line label="Estimated direct cost + commission" value={peso(totals.estimatedCost)} /><Line label="Estimated gross job profit" value={peso(totals.revenue - totals.estimatedCost)} positive={totals.revenue - totals.estimatedCost >= 0} strong /><Line label="Actual/provisional job cost" value={peso(totals.actualCost)} /><Line label="Actual/provisional profit" value={peso(totals.revenue - totals.actualCost)} positive={totals.revenue - totals.actualCost >= 0} strong /></div></Panel>\n          <Panel title="Control totals"><div className="space-y-2 text-sm"><Line label="Approved/active jobs" value={String(jobs.length)} /><Line label="Jobs with receivables" value={String(jobs.filter(j => j.receivable > 0.01).length)} /><Line label="Jobs ready for financial close" value={String(jobs.filter(j => j.receivable <= 0.01 && !j.closed).length)} /><Line label="Financially closed jobs" value={String(jobs.filter(j => j.closed).length)} /><Line label="Recorded expense entries" value={String(expenses.length)} /></div></Panel>\n        </div>\n      )}'''
new4='''      {tab === "reports" && (\n        <div className="space-y-5">\n          <Panel title="Management report" right={<div className="flex items-center gap-1 rounded-lg bg-gray-50 p-1">{([['3m','3M'],['6m','6M'],['12m','12M']] as const).map(([id,label]) => <button key={id} onClick={() => setReportRange(id)} className={`rounded-md px-2.5 py-1 text-[10px] font-semibold ${reportRange === id ? 'bg-gray-900 text-white' : 'text-gray-500 hover:bg-white'}`}>{label}</button>)}</div>}>\n            <div className="grid gap-3 sm:grid-cols-3"><Mini label="Cash in" value={peso(cashTrend.slice(reportRange === "3m" ? -3 : reportRange === "6m" ? -6 : -12).reduce((s,r) => s+r.collections,0))} /><Mini label="Production releases" value={peso(cashTrend.slice(reportRange === "3m" ? -3 : reportRange === "6m" ? -6 : -12).reduce((s,r) => s+r.releases,0))} /><Mini label="Office disbursements" value={peso(cashTrend.slice(reportRange === "3m" ? -3 : reportRange === "6m" ? -6 : -12).reduce((s,r) => s+r.expenses,0))} /></div>\n            <div className="mt-5"><CashTrendChart data={cashTrend.slice(reportRange === "3m" ? -3 : reportRange === "6m" ? -6 : -12)} /></div>\n          </Panel>\n          <div className="grid gap-5 lg:grid-cols-2">\n            <Panel title="Profitability snapshot"><div className="space-y-2 text-sm"><Line label="Revenue" value={peso(totals.dashboardRevenue)} strong /><Line label="Estimated direct cost + commission" value={peso(totals.estimatedCost)} /><Line label="Estimated gross job profit" value={peso(totals.dashboardProfit)} positive={totals.dashboardProfit >= 0} strong /><Line label="Current recorded job cost" value={peso(totals.actualCost)} /><Line label="Profit after current recorded cost" value={peso(totals.dashboardRevenue - totals.actualCost)} positive={totals.dashboardRevenue - totals.actualCost >= 0} strong /></div></Panel>\n            <Panel title="Control totals"><div className="space-y-2 text-sm"><Line label="Approved/active jobs" value={String(jobs.length)} /><Line label="Jobs with receivables" value={String(jobs.filter(j => j.receivable > 0.01).length)} /><Line label="Jobs ready for financial close" value={String(jobs.filter(j => j.receivable <= 0.01 && !j.closed).length)} /><Line label="Financially closed jobs" value={String(jobs.filter(j => j.closed).length)} /><Line label="Recorded expense entries" value={String(expenses.length)} /></div></Panel>\n          </div>\n        </div>\n      )}'''
assert old4 in s
s=s.replace(old4,new4)
# Metric component and add chart component before Panel
old5='''function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-1 text-xl font-bold tabular-nums text-gray-900">{value}</p></div>; }'''
new5='''function Metric({ label, value, hint }: { label: string; value: string; hint?: string }) { return <div className="group rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">{label}</p><span className="h-2 w-2 rounded-full bg-emerald-500 shadow-[0_0_0_3px_rgba(16,185,129,0.12)]" /></div><p className="mt-1 text-xl font-bold tabular-nums text-gray-900">{value}</p>{hint && <p className="mt-1 text-[9px] text-gray-400">{hint}</p>}</div>; }\nfunction CashTrendChart({ data }: { data: { month: string; collections: number; releases: number; expenses: number }[] }) {\n  const max = Math.max(1, ...data.flatMap(r => [r.collections, r.releases, r.expenses]));\n  return <div className="space-y-3">{data.length === 0 ? <Empty text="No cash movement recorded for the selected period." /> : data.map(r => <div key={r.month} className="grid grid-cols-[52px_1fr] items-center gap-3"><span className="text-[10px] font-semibold text-gray-500">{new Date(`${r.month}-01T00:00:00`).toLocaleDateString('en-PH',{month:'short',year:'2-digit'})}</span><div className="space-y-1"><div className="flex h-2 overflow-hidden rounded-full bg-gray-100"><span title={`Collections ${peso(r.collections)}`} className="bg-emerald-500" style={{width:`${r.collections/max*100}%`}} /><span title={`Releases ${peso(r.releases)}`} className="bg-amber-400" style={{width:`${r.releases/max*100}%`}} /><span title={`Office ${peso(r.expenses)}`} className="bg-slate-400" style={{width:`${r.expenses/max*100}%`}} /></div><div className="flex gap-3 text-[9px] text-gray-400"><span>In {peso(r.collections)}</span><span>Out {peso(r.releases+r.expenses)}</span></div></div></div>)}</div>; }'''
assert old5 in s
s=s.replace(old5,new5)
p.write_text(s)
