from pathlib import Path
p=Path('/mnt/data/accounting-repair/app/accounting/page.tsx')
s=p.read_text()
# Add trend queries to Promise all
old='''const [jobsResult, expensesResult, openingResult] = await Promise.all([\n      supabase.from("jobs").select(`job_id,status,quoted_value,final_value,clients(name),job_orders(job_order_id,funds_release_status,estimated_materials_cost,actual_materials_cost,estimated_labor_cost,actual_labor_cost,estimated_logistics_cost,actual_logistics_cost,production_stage,priority,deadline,fund_releases(amount,released_date)),payments(amount,status,type,paid_date),job_commissions(commission_id,agent_id,split_pct,commission_type,commission_value,commission_rate,amount,status,paid_date,users(name))`)\n        .in("status", ["approved", "in_production", "installed", "paid", "closed"]),\n      supabase.from("accounting_expenses").select("expense_id,job_id,category,description,payee,amount,status,expense_date,reference_no,jobs(clients(name))").order("expense_date", { ascending: false }),\n      supabase.from("accounting_opening_balances").select("*").eq("period_start", `${new Date().toISOString().slice(0, 7)}-01`).maybeSingle()\n    ]);'''
new='''const [jobsResult, expensesResult, openingResult, cashTrendResult, dashboardCashResult, dashboardReceivableResult, dashboardRevenueResult, dashboardProfitResult] = await Promise.all([\n      supabase.from("jobs").select(`job_id,status,quoted_value,final_value,clients(name),job_orders(job_order_id,funds_release_status,estimated_materials_cost,actual_materials_cost,estimated_labor_cost,actual_labor_cost,estimated_logistics_cost,actual_logistics_cost,production_stage,priority,deadline,fund_releases(amount,released_date)),payments(amount,status,type,paid_date),job_commissions(commission_id,agent_id,split_pct,commission_type,commission_value,commission_rate,amount,status,paid_date,users(name))`)\n        .in("status", ["approved", "in_production", "installed", "paid", "closed"]),\n      supabase.from("accounting_expenses").select("expense_id,job_id,category,description,payee,amount,status,expense_date,reference_no,jobs(clients(name))").order("expense_date", { ascending: false }),\n      supabase.from("accounting_opening_balances").select("*").eq("period_start", `${new Date().toISOString().slice(0, 7)}-01`).maybeSingle(),\n      supabase.from("payments").select("amount,paid_date,status").in("status", ["received","paid","completed"]).gte("paid_date", new Date(Date.now() - 365*24*60*60*1000).toISOString()).order("paid_date", { ascending: true }),\n      supabase.from("accounting_cash_position").select("current_cash_position").maybeSingle(),\n      supabase.from("accounting_customer_receivables").select("customer_receivables").maybeSingle(),\n      supabase.from("accounting_approved_revenue").select("approved_revenue").maybeSingle(),\n      supabase.from("accounting_estimated_job_profit").select("estimated_job_profit").maybeSingle()\n    ]);'''
assert old in s
s=s.replace(old,new)
# Insert dashboard error check after existing errors
old2='''if (openingResult.error) throw new Error(`Opening balance query failed: ${openingResult.error.message}`);'''
new2='''if (openingResult.error) throw new Error(`Opening balance query failed: ${openingResult.error.message}`);\n    if (cashTrendResult.error) throw new Error(`Payment trend query failed: ${cashTrendResult.error.message}`);\n    if (dashboardCashResult.error) throw new Error(`Cash dashboard query failed: ${dashboardCashResult.error.message}`);\n    if (dashboardReceivableResult.error) throw new Error(`Receivables dashboard query failed: ${dashboardReceivableResult.error.message}`);\n    if (dashboardRevenueResult.error) throw new Error(`Revenue dashboard query failed: ${dashboardRevenueResult.error.message}`);\n    if (dashboardProfitResult.error) throw new Error(`Profit dashboard query failed: ${dashboardProfitResult.error.message}`);'''
assert old2 in s
s=s.replace(old2,new2)
# Add trend transform before return
marker='''    const opening = openingResult.data;\n    const currentMonth = new Date().toISOString().slice(0, 7);'''
insert='''    const opening = openingResult.data;\n    const trendMap = new Map<string, { month: string; collections: number; releases: number; expenses: number }>();\n    const monthKey = (value: string) => value.slice(0, 7);\n    for (const p of cashTrendResult.data ?? []) {\n      const key = monthKey(p.paid_date);\n      const row = trendMap.get(key) ?? { month: key, collections: 0, releases: 0, expenses: 0 };\n      row.collections += Number(p.amount ?? 0);\n      trendMap.set(key, row);\n    }\n    for (const j of jobsResult.data ?? []) for (const jo of j.job_orders ?? []) for (const r of jo.fund_releases ?? []) {\n      const key = monthKey(r.released_date);\n      const row = trendMap.get(key) ?? { month: key, collections: 0, releases: 0, expenses: 0 };\n      row.releases += Number(r.amount ?? 0);\n      trendMap.set(key, row);\n    }\n    for (const e of expensesResult.data ?? []) if (e.status === "paid" && !e.job_id) {\n      const key = String(e.expense_date).slice(0, 7);\n      const row = trendMap.get(key) ?? { month: key, collections: 0, releases: 0, expenses: 0 };\n      row.expenses += Number(e.amount ?? 0);\n      trendMap.set(key, row);\n    }\n    const cashTrend = Array.from(trendMap.values()).sort((a,b) => a.month.localeCompare(b.month)).slice(-12);\n    const dashboardMetrics = {\n      currentCash: Number(dashboardCashResult.data?.current_cash_position ?? 0),\n      receivable: Number(dashboardReceivableResult.data?.customer_receivables ?? 0),\n      revenue: Number(dashboardRevenueResult.data?.approved_revenue ?? 0),\n      profit: Number(dashboardProfitResult.data?.estimated_job_profit ?? 0)\n    };\n    const currentMonth = new Date().toISOString().slice(0, 7);'''
assert marker in s
s=s.replace(marker,insert)
# Pass props
old3='''<AccountingWorkspace jobs={jobs} expenses={expenses} openingBalance={opening} accountingUserId={accountingUser.user_id} currentMonth={currentMonth} cashMovement={cashMovement} />'''
new3='''<AccountingWorkspace jobs={jobs} expenses={expenses} openingBalance={opening} accountingUserId={accountingUser.user_id} currentMonth={currentMonth} cashMovement={cashMovement} dashboardMetrics={dashboardMetrics} cashTrend={cashTrend} />'''
assert old3 in s
s=s.replace(old3,new3)
p.write_text(s)
